## Load Packages & Dataset

In [1]:
import numpy as np 
import pandas as pd 
import seaborn as sns
import matplotlib.pyplot as plt

from sklearn.impute import SimpleImputer
from sklearn.metrics import accuracy_score, roc_auc_score, roc_curve, confusion_matrix, auc
from sklearn.model_selection import train_test_split, cross_val_score, GridSearchCV
from sklearn.preprocessing import LabelEncoder, StandardScaler 

from sklearn.multioutput import MultiOutputClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
from sklearn.svm import SVC
from sklearn.neural_network import MLPClassifier


In [2]:
import warnings
warnings.simplefilter("ignore")

In [3]:
feature = pd.read_csv('C:/Users/18701/Downloads/training_set_features.csv',index_col="respondent_id")
label = pd.read_csv('C:/Users/18701/Downloads/training_set_labels.csv',index_col="respondent_id")

test_feature = pd.read_csv('C:/Users/18701/Downloads/test_set_features.csv',index_col="respondent_id")

In [4]:
feature.head()

h1n1_concern  h1n1_knowledge  behavioral_antiviral_meds  \
respondent_id                                                            
0                       1.0             0.0                        0.0   
1                       3.0             2.0                        0.0   
2                       1.0             1.0                        0.0   
3                       1.0             1.0                        0.0   
4                       2.0             1.0                        0.0   

               behavioral_avoidance  behavioral_face_mask  \
respondent_id                                               
0                               0.0                   0.0   
1                               1.0                   0.0   
2                               1.0                   0.0   
3                               1.0                   0.0   
4                               1.0                   0.0   

               behavioral_wash_hands  behavioral_large_gatherings  \
respondent_id                                                       
0                                0.0                          0.0   
1                                1.0                          0.0   
2                                0.0                          0.0   
3                                1.0                          1.0   
4                                1.0                          1.0   

               behavioral_outside_home  behavioral_touch_face  \
respondent_id                                                   
0                                  1.0                    1.0   
1                                  1.0                    1.0   
2                                  0.0                    0.0   
3                                  0.0                    0.0   
4                                  0.0                    1.0   

               doctor_recc_h1n1  ...             income_poverty  \
respondent_id                    ...                              
0                           0.0  ...              Below Poverty   
1                           0.0  ...              Below Poverty   
2                           NaN  ...  <= $75,000, Above Poverty   
3                           0.0  ...              Below Poverty   
4                           0.0  ...  <= $75,000, Above Poverty   

               marital_status  rent_or_own   employment_status  \
respondent_id                                                    
0                 Not Married          Own  Not in Labor Force   
1                 Not Married         Rent            Employed   
2                 Not Married          Own            Employed   
3                 Not Married         Rent  Not in Labor Force   
4                     Married          Own            Employed   

               hhs_geo_region                census_msa  household_adults  \
respondent_id                                                               
0                    oxchjgsf                   Non-MSA               0.0   
1                    bhuqouqj  MSA, Not Principle  City               0.0   
2                    qufhixun  MSA, Not Principle  City               2.0   
3                    lrircsnp       MSA, Principle City               0.0   
4                    qufhixun  MSA, Not Principle  City               1.0   

               household_children  employment_industry  employment_occupation  
respondent_id                                                                  
0                             0.0                  NaN                    NaN  
1                             0.0             pxcmvdjn               xgwztkwe  
2                             0.0             rucpziij               xtkaffoo  
3                             0.0                  NaN                    NaN  
4                             0.0             wxleyezf               emcorrxb  

[5 rows x 35 columns]

In [5]:
label.head()

h1n1_vaccine  seasonal_vaccine
respondent_id                                
0                         0                 0
1                         0                 1
2                         0                 0
3                         0                 1
4                         0                 0

In [6]:
test_feature.head()

h1n1_concern  h1n1_knowledge  behavioral_antiviral_meds  \
respondent_id                                                            
26707                   2.0             2.0                        0.0   
26708                   1.0             1.0                        0.0   
26709                   2.0             2.0                        0.0   
26710                   1.0             1.0                        0.0   
26711                   3.0             1.0                        1.0   

               behavioral_avoidance  behavioral_face_mask  \
respondent_id                                               
26707                           1.0                   0.0   
26708                           0.0                   0.0   
26709                           0.0                   1.0   
26710                           0.0                   0.0   
26711                           1.0                   0.0   

               behavioral_wash_hands  behavioral_large_gatherings  \
respondent_id                                                       
26707                            1.0                          1.0   
26708                            0.0                          0.0   
26709                            1.0                          1.0   
26710                            0.0                          0.0   
26711                            1.0                          1.0   

               behavioral_outside_home  behavioral_touch_face  \
respondent_id                                                   
26707                              0.0                    1.0   
26708                              0.0                    0.0   
26709                              1.0                    1.0   
26710                              0.0                    0.0   
26711                              1.0                    1.0   

               doctor_recc_h1n1  ...             income_poverty  \
respondent_id                    ...                              
26707                       0.0  ...                  > $75,000   
26708                       0.0  ...              Below Poverty   
26709                       0.0  ...                  > $75,000   
26710                       1.0  ...  <= $75,000, Above Poverty   
26711                       0.0  ...  <= $75,000, Above Poverty   

               marital_status  rent_or_own   employment_status  \
respondent_id                                                    
26707             Not Married         Rent            Employed   
26708             Not Married         Rent            Employed   
26709                 Married          Own            Employed   
26710                 Married          Own  Not in Labor Force   
26711             Not Married          Own            Employed   

               hhs_geo_region                census_msa  household_adults  \
respondent_id                                                               
26707                mlyzmhmf  MSA, Not Principle  City               1.0   
26708                bhuqouqj                   Non-MSA               3.0   
26709                lrircsnp                   Non-MSA               1.0   
26710                lrircsnp  MSA, Not Principle  City               1.0   
26711                lzgpxyit                   Non-MSA               0.0   

               household_children  employment_industry  employment_occupation  
respondent_id                                                                  
26707                         0.0             atmlpfrs               hfxkjkmi  
26708                         0.0             atmlpfrs               xqwwgdyp  
26709                         0.0             nduyfdeo               pvmttkik  
26710                         0.0                  NaN                    NaN  
26711                         1.0             fcxhlnwr               mxkfnird  

[5 rows x 35 columns]

In [7]:
print("Train Shape : ",feature.shape)
print("Test Shape : ",test_feature.shape)
print("Label Shape : ",label.shape)

Train Shape :  (26707, 35)
Test Shape :  (26708, 35)
Label Shape :  (26707, 2)


## Missing Values

In [8]:
feature.isnull().sum()

h1n1_concern                      92
h1n1_knowledge                   116
behavioral_antiviral_meds         71
behavioral_avoidance             208
behavioral_face_mask              19
behavioral_wash_hands             42
behavioral_large_gatherings       87
behavioral_outside_home           82
behavioral_touch_face            128
doctor_recc_h1n1                2160
doctor_recc_seasonal            2160
chronic_med_condition            971
child_under_6_months             820
health_worker                    804
health_insurance               12274
opinion_h1n1_vacc_effective      391
opinion_h1n1_risk                388
opinion_h1n1_sick_from_vacc      395
opinion_seas_vacc_effective      462
opinion_seas_risk                514
opinion_seas_sick_from_vacc      537
age_group                          0
education                       1407
race                               0
sex                                0
income_poverty                  4423
marital_status                  1408
r

In [9]:
my_imputer = SimpleImputer(missing_values=np.nan, strategy='most_frequent')

imputed_feature = pd.DataFrame(my_imputer.fit_transform(feature))
imputed_test_feature = pd.DataFrame(my_imputer.transform(test_feature))
    

In [10]:
imputed_feature.columns = feature.columns
imputed_test_feature.columns = test_feature.columns

In [11]:
imputed_feature.head()

h1n1_concern h1n1_knowledge behavioral_antiviral_meds behavioral_avoidance  \
0            1              0                         0                    0   
1            3              2                         0                    1   
2            1              1                         0                    1   
3            1              1                         0                    1   
4            2              1                         0                    1   

  behavioral_face_mask behavioral_wash_hands behavioral_large_gatherings  \
0                    0                     0                           0   
1                    0                     1                           0   
2                    0                     0                           0   
3                    0                     1                           1   
4                    0                     1                           1   

  behavioral_outside_home behavioral_touch_face doctor_recc_h1n1  ...  \
0                       1                     1                0  ...   
1                       1                     1                0  ...   
2                       0                     0                0  ...   
3                       0                     0                0  ...   
4                       0                     1                0  ...   

              income_poverty marital_status rent_or_own   employment_status  \
0              Below Poverty    Not Married         Own  Not in Labor Force   
1              Below Poverty    Not Married        Rent            Employed   
2  <= $75,000, Above Poverty    Not Married         Own            Employed   
3              Below Poverty    Not Married        Rent  Not in Labor Force   
4  <= $75,000, Above Poverty        Married         Own            Employed   

  hhs_geo_region                census_msa household_adults  \
0       oxchjgsf                   Non-MSA                0   
1       bhuqouqj  MSA, Not Principle  City                0   
2       qufhixun  MSA, Not Principle  City                2   
3       lrircsnp       MSA, Principle City                0   
4       qufhixun  MSA, Not Principle  City                1   

  household_children employment_industry employment_occupation  
0                  0            fcxhlnwr              xtkaffoo  
1                  0            pxcmvdjn              xgwztkwe  
2                  0            rucpziij              xtkaffoo  
3                  0            fcxhlnwr              xtkaffoo  
4                  0            wxleyezf              emcorrxb  

[5 rows x 35 columns]

## Categorical data

In [12]:
c_imputed_feature = imputed_feature.copy()
le = LabelEncoder()

In [13]:
c_imputed_feature['age_group'] = le.fit_transform(c_imputed_feature['age_group'])
c_imputed_feature['education'] = le.fit_transform(c_imputed_feature['education'])
c_imputed_feature['race'] = le.fit_transform(c_imputed_feature['race'])
c_imputed_feature['sex'] = le.fit_transform(c_imputed_feature['sex'])
c_imputed_feature['income_poverty'] = le.fit_transform(c_imputed_feature['income_poverty'])
c_imputed_feature['marital_status'] = le.fit_transform(c_imputed_feature['marital_status'])
c_imputed_feature['rent_or_own'] = le.fit_transform(c_imputed_feature['rent_or_own'])
c_imputed_feature['employment_status'] = le.fit_transform(c_imputed_feature['employment_status'])
c_imputed_feature['hhs_geo_region'] = le.fit_transform(c_imputed_feature['hhs_geo_region'])
c_imputed_feature['employment_industry'] = le.fit_transform(c_imputed_feature['employment_industry'])
c_imputed_feature['employment_occupation'] = le.fit_transform(c_imputed_feature['employment_occupation'])
c_imputed_feature['census_msa'] = le.fit_transform(c_imputed_feature['census_msa'])

In [14]:
c_imputed_test_feature = imputed_test_feature.copy()

c_imputed_test_feature['age_group'] = le.fit_transform(c_imputed_test_feature['age_group'])
c_imputed_test_feature['education'] = le.fit_transform(c_imputed_test_feature['education'])
c_imputed_test_feature['race'] = le.fit_transform(c_imputed_test_feature['race'])
c_imputed_test_feature['sex'] = le.fit_transform(c_imputed_test_feature['sex'])
c_imputed_test_feature['income_poverty'] = le.fit_transform(c_imputed_test_feature['income_poverty'])
c_imputed_test_feature['marital_status'] = le.fit_transform(c_imputed_test_feature['marital_status'])
c_imputed_test_feature['rent_or_own'] = le.fit_transform(c_imputed_test_feature['rent_or_own'])
c_imputed_test_feature['employment_status'] = le.fit_transform(c_imputed_test_feature['employment_status'])
c_imputed_test_feature['hhs_geo_region'] = le.fit_transform(c_imputed_test_feature['hhs_geo_region'])
c_imputed_test_feature['employment_industry'] = le.fit_transform(c_imputed_test_feature['employment_industry'])
c_imputed_test_feature['employment_occupation'] = le.fit_transform(c_imputed_test_feature['employment_occupation'])
c_imputed_test_feature['census_msa'] = le.fit_transform(c_imputed_test_feature['census_msa'])


## Modeling

In [15]:
RandomSeed = 6

X_train, X_test, y_train, y_test = train_test_split(
    c_imputed_feature,
    label, 
    test_size =0.35,
    stratify = label,
    shuffle= True,
    random_state = RandomSeed
)

### Logistic Model

In [212]:
LogisticRegression_model = MultiOutputClassifier(estimator=LogisticRegression(solver = "liblinear"))

In [213]:
LogisticRegression_model.fit(X_train, y_train)

MultiOutputClassifier(estimator=LogisticRegression(C=1.0, class_weight=None,
                                                   dual=False,
                                                   fit_intercept=True,
                                                   intercept_scaling=1,
                                                   l1_ratio=None, max_iter=100,
                                                   multi_class='auto',
                                                   n_jobs=None, penalty='l2',
                                                   random_state=None,
                                                   solver='liblinear',
                                                   tol=0.0001, verbose=0,
                                                   warm_start=False),
                      n_jobs=None)

In [214]:
pred_base = LogisticRegression_model.predict_proba(X_test)
pred_base


[array([[0.94304959, 0.05695041],
        [0.22144998, 0.77855002],
        [0.2469398 , 0.7530602 ],
        ...,
        [0.94699669, 0.05300331],
        [0.83499412, 0.16500588],
        [0.14537843, 0.85462157]]),
 array([[0.56871199, 0.43128801],
        [0.04168832, 0.95831168],
        [0.04843562, 0.95156438],
        ...,
        [0.29977177, 0.70022823],
        [0.33169786, 0.66830214],
        [0.04374629, 0.95625371]])]

In [215]:
pred_base = pd.DataFrame({"h1n1_vaccine": pred_base[0][:, 1],"seasonal_vaccine": pred_base[1][:, 1],},index = y_test.index)
pred_base.head()

h1n1_vaccine  seasonal_vaccine
respondent_id                                
12921              0.056950          0.431288
5259               0.778550          0.958312
20604              0.753060          0.951564
11600              0.064391          0.506713
8583               0.262251          0.884556

In [216]:
roc_auc_score(y_test, pred_base)

0.8390430885943736

In [217]:
parameters = {'C': [1,5,50]}


clf_LogisticRegression= GridSearchCV(LogisticRegression(solver = "liblinear"), parameters, cv=8)
clf_LogisticRegression.fit(X_train, y_train["h1n1_vaccine"])

print("For h1n1_vaccine: ",clf_LogisticRegression.best_params_,clf_LogisticRegression.best_score_)



For h1n1_vaccine:  {'C': 5} 0.8354744960938911


In [218]:
pred_best_h = clf_LogisticRegression.predict_proba(X_test)
pred_best_h

array([[0.94608327, 0.05391673],
       [0.21844133, 0.78155867],
       [0.24252747, 0.75747253],
       ...,
       [0.95007822, 0.04992178],
       [0.83517292, 0.16482708],
       [0.14626453, 0.85373547]])

In [219]:
clf_LogisticRegression.fit(X_train, y_train["seasonal_vaccine"])

print("For seasonal_vaccine: ",clf_LogisticRegression.best_params_,clf_LogisticRegression.best_score_)

For seasonal_vaccine:  {'C': 1} 0.7721063509060431


In [220]:
pred_best_s = clf_LogisticRegression.predict_proba(X_test)
pred_best_s

array([[0.56871199, 0.43128801],
       [0.04168832, 0.95831168],
       [0.04843562, 0.95156438],
       ...,
       [0.29977177, 0.70022823],
       [0.33169786, 0.66830214],
       [0.04374629, 0.95625371]])

In [221]:
pred_best = pd.DataFrame({"h1n1_vaccine": pred_best_h[:, 1],"seasonal_vaccine": pred_best_s[:, 1],},index = y_test.index)
pred_best.head()

h1n1_vaccine  seasonal_vaccine
respondent_id                                
12921              0.053917          0.431288
5259               0.781559          0.958312
20604              0.757473          0.951564
11600              0.063509          0.506713
8583               0.265471          0.884556

In [222]:
roc_auc_score(y_test, pred_best)

0.8390368646409347

## Random Forest

In [223]:
RandomForest_model =  MultiOutputClassifier(estimator=RandomForestClassifier())

In [224]:
RandomForest_model.fit(X_train, y_train)

MultiOutputClassifier(estimator=RandomForestClassifier(bootstrap=True,
                                                       ccp_alpha=0.0,
                                                       class_weight=None,
                                                       criterion='gini',
                                                       max_depth=None,
                                                       max_features='auto',
                                                       max_leaf_nodes=None,
                                                       max_samples=None,
                                                       min_impurity_decrease=0.0,
                                                       min_impurity_split=None,
                                                       min_samples_leaf=1,
                                                       min_samples_split=2,
                                                       min_weight_fraction_leaf=0.0,
                  

In [225]:
pred_base = RandomForest_model.predict_proba(X_test)
pred_base

[array([[0.91, 0.09],
        [0.4 , 0.6 ],
        [0.35, 0.65],
        ...,
        [0.93, 0.07],
        [0.72, 0.28],
        [0.24, 0.76]]),
 array([[0.55, 0.45],
        [0.14, 0.86],
        [0.02, 0.98],
        ...,
        [0.3 , 0.7 ],
        [0.42, 0.58],
        [0.13, 0.87]])]

In [226]:
pred_base = pd.DataFrame({"h1n1_vaccine": pred_base[0][:, 1],"seasonal_vaccine": pred_base[1][:, 1],},index = y_test.index)

In [227]:
pred_base.head()

h1n1_vaccine  seasonal_vaccine
respondent_id                                
12921                  0.09              0.45
5259                   0.60              0.86
20604                  0.65              0.98
11600                  0.06              0.70
8583                   0.36              0.87

In [228]:
roc_auc_score(y_test, pred_base)

0.8345640840439086

In [229]:
parameters = {'n_estimators':[1,20,100]}

clf_RandomForest= GridSearchCV(RandomForestClassifier(), parameters, cv=8)
clf_RandomForest.fit(X_train, y_train)

clf_RandomForest.best_params_,clf_RandomForest.best_score_




({'n_estimators': 100}, 0.6636331380810032)

In [230]:
pred_best = clf_RandomForest.predict_proba(X_test)
pred_best

[array([[0.93, 0.07],
        [0.35, 0.65],
        [0.31, 0.69],
        ...,
        [0.93, 0.07],
        [0.79, 0.21],
        [0.23, 0.77]]),
 array([[0.41, 0.59],
        [0.09, 0.91],
        [0.06, 0.94],
        ...,
        [0.36, 0.64],
        [0.48, 0.52],
        [0.05, 0.95]])]

In [231]:
pred_best = pd.DataFrame({"h1n1_vaccine": pred_best[0][:, 1],"seasonal_vaccine": pred_best[1][:, 1],},index = y_test.index)
pred_best

h1n1_vaccine  seasonal_vaccine
respondent_id                                
12921                  0.07              0.59
5259                   0.65              0.91
20604                  0.69              0.94
11600                  0.04              0.72
8583                   0.31              0.78
...                     ...               ...
21244                  0.21              0.64
22134                  0.06              0.68
19653                  0.07              0.64
6431                   0.21              0.52
16158                  0.77              0.95

[9348 rows x 2 columns]

In [232]:
roc_auc_score(y_test, pred_best)

0.834597750482943

## SVM

In [233]:
SVM =  MultiOutputClassifier(estimator=SVC(gamma='auto',probability=True))

In [234]:
SVM.fit(X_train, y_train)

MultiOutputClassifier(estimator=SVC(C=1.0, break_ties=False, cache_size=200,
                                    class_weight=None, coef0=0.0,
                                    decision_function_shape='ovr', degree=3,
                                    gamma='auto', kernel='rbf', max_iter=-1,
                                    probability=True, random_state=None,
                                    shrinking=True, tol=0.001, verbose=False),
                      n_jobs=None)

In [235]:
pred_base = SVM.predict_proba(X_test)
pred_base

[array([[0.88295499, 0.11704501],
        [0.40392424, 0.59607576],
        [0.18188858, 0.81811142],
        ...,
        [0.94908418, 0.05091582],
        [0.85519002, 0.14480998],
        [0.06619252, 0.93380748]]),
 array([[0.45824052, 0.54175948],
        [0.13647364, 0.86352636],
        [0.07056278, 0.92943722],
        ...,
        [0.329684  , 0.670316  ],
        [0.24631996, 0.75368004],
        [0.09367118, 0.90632882]])]

In [236]:
pred_base = pd.DataFrame({"h1n1_vaccine": pred_base[0][:, 1],"seasonal_vaccine": pred_base[1][:, 1],},index = y_test.index)

In [237]:
roc_auc_score(y_test, pred_base)

0.8284344286690173

In [238]:
parameters = {'C':[1,5,20]}

clf_SVM = GridSearchCV(SVC(gamma='auto',probability=True), parameters, cv=8)
clf_SVM.fit(X_train, y_train["h1n1_vaccine"])

print("For h1n1_vaccine: ",clf_SVM.best_params_,clf_SVM.best_score_)

For h1n1_vaccine:  {'C': 1} 0.830404920188751


In [239]:
pred_best_h = clf_SVM.predict_proba(X_test)
pred_best_h

array([[0.88209387, 0.11790613],
       [0.40956434, 0.59043566],
       [0.18748632, 0.81251368],
       ...,
       [0.9480545 , 0.0519455 ],
       [0.854551  , 0.145449  ],
       [0.0694658 , 0.9305342 ]])

In [240]:
clf_SVM.fit(X_train, y_train["seasonal_vaccine"])

print("For seasonal_vaccine: ",clf_SVM.best_params_,clf_SVM.best_score_)

For seasonal_vaccine:  {'C': 1} 0.7732591151393855


In [241]:
pred_best_s = clf_SVM.predict_proba(X_test)
pred_best_s

array([[0.45884189, 0.54115811],
       [0.13777145, 0.86222855],
       [0.07153013, 0.92846987],
       ...,
       [0.33082856, 0.66917144],
       [0.24766937, 0.75233063],
       [0.09478973, 0.90521027]])

In [242]:
pred_best = pd.DataFrame({"h1n1_vaccine": pred_best_h[:, 1],"seasonal_vaccine": pred_best_s[:, 1],},index = y_test.index)
pred_best.head()

h1n1_vaccine  seasonal_vaccine
respondent_id                                
12921              0.117906          0.541158
5259               0.590436          0.862229
20604              0.812514          0.928470
11600              0.101104          0.744627
8583               0.161436          0.932987

In [243]:
roc_auc_score(y_test, pred_best)

0.828429843056198

## ANN

In [16]:
import tensorflow as tf

In [17]:
ann = tf.keras.models.Sequential()

ann.add(tf.keras.layers.Dense(units = 64, activation = 'relu'))
ann.add(tf.keras.layers.Dense(units = 32, activation = 'relu'))
ann.add(tf.keras.layers.Dense(units = 16, activation = 'relu'))
ann.add(tf.keras.layers.Dense(units = 1, activation = 'sigmoid'))    
ann.compile(optimizer="SGD", loss='binary_crossentropy', metrics=['accuracy'])

In [18]:
X_train_ = np.asarray(X_train).astype(np.float32)
X_test_ = np.asarray(X_test).astype(np.float32)
y_train_h = np.asarray(y_train["h1n1_vaccine"]).astype(np.float32)
y_train_s = np.asarray(y_train["seasonal_vaccine"]).astype(np.float32)

In [19]:
X_test_

array([[ 2.,  1.,  0., ...,  0.,  4., 21.],
       [ 3.,  1.,  0., ...,  0., 12.,  2.],
       [ 3.,  2.,  0., ...,  0.,  4., 21.],
       ...,
       [ 1.,  1.,  0., ...,  1.,  4., 11.],
       [ 2.,  2.,  0., ...,  1.,  2., 21.],
       [ 2.,  2.,  0., ...,  0.,  4.,  2.]], dtype=float32)

In [20]:
y_train = np.asarray(y_train).astype(np.float32)

In [21]:
y_train

array([[0., 1.],
       [1., 1.],
       [1., 1.],
       ...,
       [0., 1.],
       [0., 1.],
       [0., 0.]], dtype=float32)

In [22]:
y_train_h

array([0., 1., 1., ..., 0., 0., 0.], dtype=float32)

In [23]:
y_train_s

array([1., 1., 1., ..., 1., 1., 0.], dtype=float32)

In [24]:
ann.fit(X_train_, y_train_h, batch_size = 1024, epochs = 1000)

Epoch 1/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.5735 - accuracy: 0.7490
Epoch 2/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.5217 - accuracy: 0.7824
Epoch 3/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.5121 - accuracy: 0.7850
Epoch 4/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.5048 - accuracy: 0.7858
Epoch 5/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.4992 - accuracy: 0.7871
Epoch 6/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.4946 - accuracy: 0.7882
Epoch 7/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.4906 - accuracy: 0.7890
Epoch 8/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.4870 - accuracy: 0.7896
Epoch 9/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.4834 - accuracy: 0.7904
Epoch 10/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.4799 - accuracy: 0.7908

17/17 [==============================] - 0s 2ms/step - loss: 0.4111 - accuracy: 0.8249
Epoch 83/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.4145 - accuracy: 0.8234
Epoch 84/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.4103 - accuracy: 0.8263
Epoch 85/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.4095 - accuracy: 0.8239
Epoch 86/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.4328 - accuracy: 0.8147
Epoch 87/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.4107 - accuracy: 0.8259
Epoch 88/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.4287 - accuracy: 0.8175
Epoch 89/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.4129 - accuracy: 0.8242
Epoch 90/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.4170 - accuracy: 0.8220
Epoch 91/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.4222 - accuracy: 0.8226
Epoc

17/17 [==============================] - 0s 2ms/step - loss: 0.3977 - accuracy: 0.8312
Epoch 163/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.4049 - accuracy: 0.8292
Epoch 164/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.3999 - accuracy: 0.8329
Epoch 165/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.3977 - accuracy: 0.8315
Epoch 166/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.3998 - accuracy: 0.8300
Epoch 167/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.3995 - accuracy: 0.8299
Epoch 168/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.4007 - accuracy: 0.8309
Epoch 169/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.4013 - accuracy: 0.8311
Epoch 170/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.3968 - accuracy: 0.8312
Epoch 171/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.4056 - accuracy: 0.

17/17 [==============================] - 0s 2ms/step - loss: 0.3970 - accuracy: 0.8331
Epoch 243/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.4001 - accuracy: 0.8315
Epoch 244/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.3949 - accuracy: 0.8326
Epoch 245/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.3996 - accuracy: 0.8327
Epoch 246/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.3954 - accuracy: 0.8339
Epoch 247/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.3908 - accuracy: 0.8349
Epoch 248/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.3903 - accuracy: 0.8345
Epoch 249/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.3929 - accuracy: 0.8359
Epoch 250/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.3986 - accuracy: 0.8327
Epoch 251/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.3928 - accuracy: 0.

17/17 [==============================] - 0s 2ms/step - loss: 0.3902 - accuracy: 0.8354
Epoch 323/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.4001 - accuracy: 0.8320
Epoch 324/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.3970 - accuracy: 0.8328
Epoch 325/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.3871 - accuracy: 0.8359
Epoch 326/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.3914 - accuracy: 0.8350
Epoch 327/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.3920 - accuracy: 0.8360
Epoch 328/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.3890 - accuracy: 0.8347
Epoch 329/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.3878 - accuracy: 0.8371
Epoch 330/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.3888 - accuracy: 0.8370
Epoch 331/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.3866 - accuracy: 0.

17/17 [==============================] - 0s 2ms/step - loss: 0.3845 - accuracy: 0.8380
Epoch 403/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.3882 - accuracy: 0.8355
Epoch 404/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.3914 - accuracy: 0.8358
Epoch 405/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.3869 - accuracy: 0.8377
Epoch 406/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.3882 - accuracy: 0.8375
Epoch 407/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.3900 - accuracy: 0.8358
Epoch 408/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.3914 - accuracy: 0.8349
Epoch 409/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.3898 - accuracy: 0.8374
Epoch 410/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.3848 - accuracy: 0.8373
Epoch 411/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.3890 - accuracy: 0.

17/17 [==============================] - 0s 2ms/step - loss: 0.3826 - accuracy: 0.8393
Epoch 483/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.3834 - accuracy: 0.8374
Epoch 484/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.3889 - accuracy: 0.8360
Epoch 485/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.3866 - accuracy: 0.8373
Epoch 486/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.3831 - accuracy: 0.8385
Epoch 487/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.3893 - accuracy: 0.8356
Epoch 488/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.3830 - accuracy: 0.8390
Epoch 489/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.3808 - accuracy: 0.8396
Epoch 490/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.3808 - accuracy: 0.8390
Epoch 491/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.3893 - accuracy: 0.

17/17 [==============================] - 0s 2ms/step - loss: 0.3808 - accuracy: 0.8407
Epoch 563/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.3801 - accuracy: 0.8391
Epoch 564/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.3802 - accuracy: 0.8411
Epoch 565/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.3815 - accuracy: 0.8386
Epoch 566/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.3798 - accuracy: 0.8389
Epoch 567/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.3802 - accuracy: 0.8392
Epoch 568/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.3796 - accuracy: 0.8400
Epoch 569/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.3850 - accuracy: 0.8399
Epoch 570/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.3802 - accuracy: 0.8393
Epoch 571/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.3792 - accuracy: 0.

17/17 [==============================] - 0s 2ms/step - loss: 0.3767 - accuracy: 0.8419
Epoch 643/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.3761 - accuracy: 0.8416
Epoch 644/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.3873 - accuracy: 0.8353
Epoch 645/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.3775 - accuracy: 0.8408
Epoch 646/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.3809 - accuracy: 0.8405
Epoch 647/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.3834 - accuracy: 0.8399
Epoch 648/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.3769 - accuracy: 0.8409
Epoch 649/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.3772 - accuracy: 0.8420
Epoch 650/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.3777 - accuracy: 0.8417
Epoch 651/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.3801 - accuracy: 0.

17/17 [==============================] - 0s 2ms/step - loss: 0.3774 - accuracy: 0.8398
Epoch 723/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.3793 - accuracy: 0.8397
Epoch 724/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.3809 - accuracy: 0.8403
Epoch 725/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.3755 - accuracy: 0.8414
Epoch 726/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.3786 - accuracy: 0.8396
Epoch 727/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.3822 - accuracy: 0.8390
Epoch 728/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.3759 - accuracy: 0.8416
Epoch 729/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.3764 - accuracy: 0.8401
Epoch 730/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.3775 - accuracy: 0.8417
Epoch 731/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.3815 - accuracy: 0.

17/17 [==============================] - 0s 2ms/step - loss: 0.3766 - accuracy: 0.8409
Epoch 803/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.3764 - accuracy: 0.8431
Epoch 804/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.3769 - accuracy: 0.8411
Epoch 805/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.3764 - accuracy: 0.8418
Epoch 806/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.3728 - accuracy: 0.8426
Epoch 807/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.3780 - accuracy: 0.8414
Epoch 808/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.3763 - accuracy: 0.8433
Epoch 809/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.3750 - accuracy: 0.8423
Epoch 810/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.3746 - accuracy: 0.8425
Epoch 811/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.3755 - accuracy: 0.

17/17 [==============================] - 0s 2ms/step - loss: 0.3726 - accuracy: 0.8430
Epoch 883/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.3747 - accuracy: 0.8411
Epoch 884/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.3719 - accuracy: 0.8438
Epoch 885/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.3729 - accuracy: 0.8439
Epoch 886/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.3728 - accuracy: 0.8438
Epoch 887/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.3723 - accuracy: 0.8447
Epoch 888/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.3738 - accuracy: 0.8411
Epoch 889/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.3782 - accuracy: 0.8421
Epoch 890/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.3769 - accuracy: 0.8433
Epoch 891/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.3717 - accuracy: 0.

17/17 [==============================] - 0s 2ms/step - loss: 0.3707 - accuracy: 0.8455
Epoch 963/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.3754 - accuracy: 0.8415
Epoch 964/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.3753 - accuracy: 0.8433
Epoch 965/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.3744 - accuracy: 0.8409
Epoch 966/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.3769 - accuracy: 0.8419
Epoch 967/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.3735 - accuracy: 0.8428
Epoch 968/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.3696 - accuracy: 0.8443
Epoch 969/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.3709 - accuracy: 0.8452
Epoch 970/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.3736 - accuracy: 0.8407
Epoch 971/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.3744 - accuracy: 0.

In [25]:
pred_h = ann.predict(X_test_)

In [26]:
pred_h

array([[0.03136197],
       [0.6494818 ],
       [0.61664987],
       ...,
       [0.09084901],
       [0.21915567],
       [0.80415213]], dtype=float32)

In [32]:
ann.fit(X_train_, y_train_s, batch_size = 1024, epochs = 1000)

Epoch 1/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.4565 - accuracy: 0.7897
Epoch 2/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.4538 - accuracy: 0.7897
Epoch 3/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.4553 - accuracy: 0.7858
Epoch 4/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.4564 - accuracy: 0.7897
Epoch 5/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.4560 - accuracy: 0.7896
Epoch 6/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.4581 - accuracy: 0.7871
Epoch 7/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.4574 - accuracy: 0.7874
Epoch 8/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.4543 - accuracy: 0.7878
Epoch 9/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.4548 - accuracy: 0.7914
Epoch 10/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.4544 - accuracy: 0.7895

17/17 [==============================] - 0s 2ms/step - loss: 0.4613 - accuracy: 0.7843
Epoch 83/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.4636 - accuracy: 0.7847
Epoch 84/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.4547 - accuracy: 0.7900
Epoch 85/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.4537 - accuracy: 0.7908
Epoch 86/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.4557 - accuracy: 0.7887
Epoch 87/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.4566 - accuracy: 0.7870
Epoch 88/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.4535 - accuracy: 0.7890
Epoch 89/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.4536 - accuracy: 0.7881
Epoch 90/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.4571 - accuracy: 0.7855
Epoch 91/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.4537 - accuracy: 0.7879
Epoc

17/17 [==============================] - 0s 2ms/step - loss: 0.4535 - accuracy: 0.7907
Epoch 162/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.4550 - accuracy: 0.7898
Epoch 163/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.4567 - accuracy: 0.7855
Epoch 164/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.4536 - accuracy: 0.7892
Epoch 165/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.4546 - accuracy: 0.7897
Epoch 166/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.4544 - accuracy: 0.7903
Epoch 167/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.4515 - accuracy: 0.7889
Epoch 168/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.4522 - accuracy: 0.7901
Epoch 169/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.4528 - accuracy: 0.7891
Epoch 170/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.4555 - accuracy: 0.

17/17 [==============================] - 0s 2ms/step - loss: 0.4525 - accuracy: 0.7903
Epoch 242/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.4573 - accuracy: 0.7858
Epoch 243/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.4527 - accuracy: 0.7893
Epoch 244/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.4526 - accuracy: 0.7912
Epoch 245/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.4547 - accuracy: 0.7908
Epoch 246/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.4533 - accuracy: 0.7904
Epoch 247/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.4523 - accuracy: 0.7892
Epoch 248/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.4555 - accuracy: 0.7892
Epoch 249/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.4541 - accuracy: 0.7896
Epoch 250/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.4529 - accuracy: 0.

17/17 [==============================] - 0s 2ms/step - loss: 0.4543 - accuracy: 0.7902
Epoch 322/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.4504 - accuracy: 0.7913
Epoch 323/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.4507 - accuracy: 0.7923
Epoch 324/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.4545 - accuracy: 0.7875
Epoch 325/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.4532 - accuracy: 0.7901
Epoch 326/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.4539 - accuracy: 0.7898
Epoch 327/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.4532 - accuracy: 0.7901
Epoch 328/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.4494 - accuracy: 0.7918
Epoch 329/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.4522 - accuracy: 0.7907
Epoch 330/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.4528 - accuracy: 0.

17/17 [==============================] - 0s 2ms/step - loss: 0.4503 - accuracy: 0.7922
Epoch 402/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.4532 - accuracy: 0.7880
Epoch 403/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.4493 - accuracy: 0.7938
Epoch 404/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.4502 - accuracy: 0.7917
Epoch 405/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.4497 - accuracy: 0.7923
Epoch 406/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.4500 - accuracy: 0.7908
Epoch 407/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.4491 - accuracy: 0.7917
Epoch 408/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.4472 - accuracy: 0.7942
Epoch 409/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.4489 - accuracy: 0.7935
Epoch 410/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.4519 - accuracy: 0.

17/17 [==============================] - 0s 2ms/step - loss: 0.4495 - accuracy: 0.7912
Epoch 482/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.4523 - accuracy: 0.7891
Epoch 483/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.4486 - accuracy: 0.7922
Epoch 484/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.4469 - accuracy: 0.7930
Epoch 485/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.4471 - accuracy: 0.7931
Epoch 486/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.4484 - accuracy: 0.7909
Epoch 487/1000
17/17 [==============================] - ETA: 0s - loss: 0.4573 - accuracy: 0.78 - 0s 2ms/step - loss: 0.4505 - accuracy: 0.7907
Epoch 488/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.4477 - accuracy: 0.7923
Epoch 489/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.4474 - accuracy: 0.7924
Epoch 490/1000
17/17 [==============================] -

17/17 [==============================] - 0s 2ms/step - loss: 0.4523 - accuracy: 0.7877
Epoch 562/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.4453 - accuracy: 0.7947
Epoch 563/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.4454 - accuracy: 0.7942
Epoch 564/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.4476 - accuracy: 0.7916
Epoch 565/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.4525 - accuracy: 0.7891
Epoch 566/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.4492 - accuracy: 0.7913
Epoch 567/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.4495 - accuracy: 0.7927
Epoch 568/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.4593 - accuracy: 0.7830
Epoch 569/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.4480 - accuracy: 0.7921
Epoch 570/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.4508 - accuracy: 0.

Epoch 641/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.4487 - accuracy: 0.7941
Epoch 642/1000
17/17 [==============================] - 0s 3ms/step - loss: 0.4468 - accuracy: 0.7929
Epoch 643/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.4477 - accuracy: 0.7947
Epoch 644/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.4458 - accuracy: 0.7932
Epoch 645/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.4542 - accuracy: 0.7886
Epoch 646/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.4454 - accuracy: 0.7938
Epoch 647/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.4492 - accuracy: 0.7917
Epoch 648/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.4466 - accuracy: 0.7933
Epoch 649/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.4452 - accuracy: 0.7946
Epoch 650/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.4440

17/17 [==============================] - 0s 2ms/step - loss: 0.4483 - accuracy: 0.7899
Epoch 721/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.4434 - accuracy: 0.7943
Epoch 722/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.4440 - accuracy: 0.7927
Epoch 723/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.4446 - accuracy: 0.7934
Epoch 724/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.4456 - accuracy: 0.7920
Epoch 725/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.4507 - accuracy: 0.7898
Epoch 726/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.4452 - accuracy: 0.7949
Epoch 727/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.4443 - accuracy: 0.7928
Epoch 728/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.4484 - accuracy: 0.7920
Epoch 729/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.4542 - accuracy: 0.

17/17 [==============================] - 0s 2ms/step - loss: 0.4481 - accuracy: 0.7925
Epoch 801/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.4448 - accuracy: 0.7930
Epoch 802/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.4516 - accuracy: 0.7884
Epoch 803/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.4437 - accuracy: 0.7941
Epoch 804/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.4501 - accuracy: 0.7910
Epoch 805/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.4445 - accuracy: 0.7935
Epoch 806/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.4444 - accuracy: 0.7930
Epoch 807/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.4456 - accuracy: 0.7937
Epoch 808/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.4428 - accuracy: 0.7949
Epoch 809/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.4453 - accuracy: 0.

17/17 [==============================] - 0s 2ms/step - loss: 0.4469 - accuracy: 0.7913
Epoch 881/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.4430 - accuracy: 0.7947
Epoch 882/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.4455 - accuracy: 0.7931
Epoch 883/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.4440 - accuracy: 0.7929
Epoch 884/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.4471 - accuracy: 0.7901
Epoch 885/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.4406 - accuracy: 0.7965
Epoch 886/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.4436 - accuracy: 0.7934
Epoch 887/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.4423 - accuracy: 0.7951
Epoch 888/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.4409 - accuracy: 0.7946
Epoch 889/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.4434 - accuracy: 0.

17/17 [==============================] - 0s 2ms/step - loss: 0.4461 - accuracy: 0.7938
Epoch 961/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.4426 - accuracy: 0.7941
Epoch 962/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.4426 - accuracy: 0.7962
Epoch 963/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.4424 - accuracy: 0.7943
Epoch 964/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.4411 - accuracy: 0.7971
Epoch 965/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.4413 - accuracy: 0.7959
Epoch 966/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.4419 - accuracy: 0.7957
Epoch 967/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.4389 - accuracy: 0.7969
Epoch 968/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.4411 - accuracy: 0.7959
Epoch 969/1000
17/17 [==============================] - 0s 2ms/step - loss: 0.4398 - accuracy: 0.

In [33]:
pred_s = ann.predict(X_test_)
pred_s

array([[0.3693462 ],
       [0.96038926],
       [0.9101472 ],
       ...,
       [0.66811544],
       [0.674186  ],
       [0.82430696]], dtype=float32)

In [59]:
def OneDimension(array):
    return [float(i) for i in array]
        

In [35]:
pred_s_ = OneDimension(pred_s)
pred_s_

[0.3693462014198303,
 0.960389256477356,
 0.9101471900939941,
 0.5988731384277344,
 0.8633575439453125,
 0.2569848895072937,
 0.039252251386642456,
 0.8979413509368896,
 0.0823860764503479,
 0.046039730310440063,
 0.09855338931083679,
 0.8054114580154419,
 0.08700805902481079,
 0.8216857314109802,
 0.9264630675315857,
 0.09820634126663208,
 0.3110899329185486,
 0.3252659738063812,
 0.2425951063632965,
 0.13704487681388855,
 0.8526535034179688,
 0.6032384037971497,
 0.1603013277053833,
 0.8454891443252563,
 0.78661048412323,
 0.8079633712768555,
 0.0917990505695343,
 0.11705100536346436,
 0.833702802658081,
 0.07202553749084473,
 0.11611577868461609,
 0.03039523959159851,
 0.06605520844459534,
 0.5264283418655396,
 0.9211631417274475,
 0.4609980285167694,
 0.21995297074317932,
 0.9540671110153198,
 0.06939315795898438,
 0.18489402532577515,
 0.0857488214969635,
 0.09622323513031006,
 0.12769007682800293,
 0.09725892543792725,
 0.9136192798614502,
 0.6967700123786926,
 0.4521154761314392

In [36]:
pred_h_ = OneDimension(pred_h)
pred_h_

[0.03136196732521057,
 0.6494817733764648,
 0.616649866104126,
 0.023791879415512085,
 0.25330227613449097,
 0.09440898895263672,
 0.03129005432128906,
 0.10043969750404358,
 0.16691553592681885,
 0.015928655862808228,
 0.10290795564651489,
 0.828556478023529,
 0.1497456133365631,
 0.6452192664146423,
 0.05380323529243469,
 0.12459522485733032,
 0.11647984385490417,
 0.0648411214351654,
 0.03984743356704712,
 0.2674294114112854,
 0.699146568775177,
 0.6635158061981201,
 0.0818200409412384,
 0.5963848829269409,
 0.09347456693649292,
 0.035122036933898926,
 0.03830748796463013,
 0.06254726648330688,
 0.6460758447647095,
 0.043944209814071655,
 0.12475159764289856,
 0.014501780271530151,
 0.06840583682060242,
 0.061956167221069336,
 0.08386984467506409,
 0.10813131928443909,
 0.0669650137424469,
 0.8573393821716309,
 0.04113847017288208,
 0.03201955556869507,
 0.16901618242263794,
 0.06078323721885681,
 0.20659375190734863,
 0.12889957427978516,
 0.7551769018173218,
 0.4099809527397156,
 

In [37]:
pred = pd.DataFrame({"h1n1_vaccine": pred_h_,"seasonal_vaccine": pred_s_},index = y_test.index)
pred.head()

h1n1_vaccine  seasonal_vaccine
respondent_id                                
12921              0.031362          0.369346
5259               0.649482          0.960389
20604              0.616650          0.910147
11600              0.023792          0.598873
8583               0.253302          0.863358

In [256]:
roc_auc_score(y_test, pred)

0.8372994772414529

## Predictions for test dataset

In [45]:
c_imputed_test_feature

h1n1_concern h1n1_knowledge behavioral_antiviral_meds  \
0                2              2                         0   
1                1              1                         0   
2                2              2                         0   
3                1              1                         0   
4                3              1                         1   
...            ...            ...                       ...   
26703            1              1                         0   
26704            3              1                         0   
26705            0              1                         0   
26706            3              1                         0   
26707            2              1                         0   

      behavioral_avoidance behavioral_face_mask behavioral_wash_hands  \
0                        1                    0                     1   
1                        0                    0                     0   
2                        0                    1                     1   
3                        0                    0                     0   
4                        1                    0                     1   
...                    ...                  ...                   ...   
26703                    1                    0                     1   
26704                    1                    0                     1   
26705                    0                    0                     0   
26706                    1                    0                     1   
26707                    0                    0                     1   

      behavioral_large_gatherings behavioral_outside_home  \
0                               1                       0   
1                               0                       0   
2                               1                       1   
3                               0                       0   
4                               1                       1   
...                           ...                     ...   
26703                           0                       0   
26704                           1                       1   
26705                           0                       0   
26706                           0                       1   
26707                           0                       0   

      behavioral_touch_face doctor_recc_h1n1  ... income_poverty  \
0                         1                0  ...              1   
1                         0                0  ...              2   
2                         1                0  ...              1   
3                         0                1  ...              0   
4                         1                0  ...              0   
...                     ...              ...  ...            ...   
26703                     1                1  ...              0   
26704                     1                0  ...              2   
26705                     0                0  ...              2   
26706                     0                0  ...              0   
26707                     1                1  ...              0   

      marital_status rent_or_own employment_status hhs_geo_region census_msa  \
0                  1           1                 0              7          0   
1                  1           1                 0              1          2   
2                  0           0                 0              5          2   
3                  0           0                 1              5          0   
4                  1           0                 0              6          2   
...              ...         ...               ...            ...        ...   
26703              0           0                 0              2          1   
26704              0           1                 0              9          2   
26705              1           1                 1              9          0   
26706              0  

In [46]:
c_imputed_test_feature_ = np.asarray(c_imputed_test_feature).astype(np.float32)
c_imputed_test_feature_

array([[ 2.,  2.,  0., ...,  0.,  1.,  7.],
       [ 1.,  1.,  0., ...,  0.,  1., 20.],
       [ 2.,  2.,  0., ...,  0., 10., 12.],
       ...,
       [ 0.,  1.,  0., ...,  0.,  4., 21.],
       [ 3.,  1.,  0., ...,  0.,  4., 21.],
       [ 2.,  1.,  0., ...,  0.,  4., 21.]], dtype=float32)

In [53]:
c_imputed_feature_ = np.asarray(c_imputed_feature).astype(np.float32)
c_imputed_feature_

array([[ 1.,  0.,  0., ...,  0.,  4., 21.],
       [ 3.,  2.,  0., ...,  0., 12., 19.],
       [ 1.,  1.,  0., ...,  0., 14., 21.],
       ...,
       [ 2.,  2.,  0., ...,  0.,  4., 21.],
       [ 1.,  1.,  0., ...,  0.,  4.,  6.],
       [ 0.,  0.,  0., ...,  0.,  4., 21.]], dtype=float32)

In [39]:
label_h = np.asarray(label_h["h1n1_vaccine"]).astype(np.float32)

h1n1_vaccine  seasonal_vaccine
respondent_id                                
0                         0                 0
1                         0                 1
2                         0                 0
3                         0                 1
4                         0                 0
...                     ...               ...
26702                     0                 0
26703                     0                 0
26704                     0                 1
26705                     0                 0
26706                     0                 0

[26707 rows x 2 columns]

In [41]:
label_h = np.asarray(label["h1n1_vaccine"]).astype(np.float32)
label_h

array([0., 0., 0., ..., 0., 0., 0.], dtype=float32)

In [42]:
label_s = np.asarray(label["seasonal_vaccine"]).astype(np.float32)
label_s

array([0., 1., 0., ..., 1., 0., 0.], dtype=float32)

In [55]:
ann.fit(c_imputed_feature_, label_h, batch_size = 1024, epochs = 1000)

Epoch 1/1000
27/27 [==============================] - 0s 3ms/step - loss: 0.4857 - accuracy: 0.7810
Epoch 2/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.4528 - accuracy: 0.7990
Epoch 3/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.4406 - accuracy: 0.8078
Epoch 4/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.4329 - accuracy: 0.8126
Epoch 5/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.4250 - accuracy: 0.8166
Epoch 6/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.4197 - accuracy: 0.8185
Epoch 7/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.4154 - accuracy: 0.8221
Epoch 8/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.4117 - accuracy: 0.8229
Epoch 9/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.4084 - accuracy: 0.8260
Epoch 10/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.4111 - accuracy: 0.8237

27/27 [==============================] - 0s 2ms/step - loss: 0.3793 - accuracy: 0.8385
Epoch 82/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.3816 - accuracy: 0.8378
Epoch 83/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.3791 - accuracy: 0.8390
Epoch 84/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.3758 - accuracy: 0.8400
Epoch 85/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.3772 - accuracy: 0.8390
Epoch 86/1000
27/27 [==============================] - 0s 3ms/step - loss: 0.3780 - accuracy: 0.8393
Epoch 87/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.3763 - accuracy: 0.8397
Epoch 88/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.3804 - accuracy: 0.8376
Epoch 89/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.3775 - accuracy: 0.8386
Epoch 90/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.3754 - accuracy: 0.8391
Epoc

27/27 [==============================] - 0s 2ms/step - loss: 0.3742 - accuracy: 0.8405
Epoch 162/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.3748 - accuracy: 0.8419
Epoch 163/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.3711 - accuracy: 0.8423
Epoch 164/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.3714 - accuracy: 0.8425
Epoch 165/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.3709 - accuracy: 0.8424
Epoch 166/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.3726 - accuracy: 0.8430
Epoch 167/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.3707 - accuracy: 0.8423
Epoch 168/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.3696 - accuracy: 0.8439
Epoch 169/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.3726 - accuracy: 0.8417
Epoch 170/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.3708 - accuracy: 0.

27/27 [==============================] - 0s 2ms/step - loss: 0.3697 - accuracy: 0.8438
Epoch 241/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.3738 - accuracy: 0.8408
Epoch 242/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.3683 - accuracy: 0.8440
Epoch 243/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.3684 - accuracy: 0.8450
Epoch 244/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.3680 - accuracy: 0.8444
Epoch 245/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.3703 - accuracy: 0.8438
Epoch 246/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.3680 - accuracy: 0.8443
Epoch 247/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.3693 - accuracy: 0.8426
Epoch 248/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.3696 - accuracy: 0.8433
Epoch 249/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.3676 - accuracy: 0.

27/27 [==============================] - 0s 2ms/step - loss: 0.3652 - accuracy: 0.8449
Epoch 320/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.3696 - accuracy: 0.8429
Epoch 321/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.3654 - accuracy: 0.8442
Epoch 322/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.3654 - accuracy: 0.8450
Epoch 323/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.3685 - accuracy: 0.8440
Epoch 324/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.3681 - accuracy: 0.8422
Epoch 325/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.3646 - accuracy: 0.8453
Epoch 326/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.3681 - accuracy: 0.8433
Epoch 327/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.3665 - accuracy: 0.8444
Epoch 328/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.3673 - accuracy: 0.

27/27 [==============================] - 0s 2ms/step - loss: 0.3641 - accuracy: 0.8460: 0s - loss: 0.3639 - accuracy: 0.84
Epoch 399/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.3637 - accuracy: 0.8459
Epoch 400/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.3655 - accuracy: 0.8452
Epoch 401/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.3631 - accuracy: 0.8461
Epoch 402/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.3644 - accuracy: 0.8443
Epoch 403/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.3631 - accuracy: 0.8450
Epoch 404/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.3655 - accuracy: 0.8443
Epoch 405/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.3685 - accuracy: 0.8429
Epoch 406/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.3657 - accuracy: 0.8459
Epoch 407/1000
27/27 [==============================] - 0s 2m

27/27 [==============================] - 0s 2ms/step - loss: 0.3651 - accuracy: 0.8448
Epoch 478/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.3677 - accuracy: 0.8431
Epoch 479/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.3685 - accuracy: 0.8433
Epoch 480/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.3630 - accuracy: 0.8449
Epoch 481/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.3637 - accuracy: 0.8447
Epoch 482/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.3645 - accuracy: 0.8455
Epoch 483/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.3640 - accuracy: 0.8459
Epoch 484/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.3617 - accuracy: 0.8461
Epoch 485/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.3652 - accuracy: 0.8460
Epoch 486/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.3623 - accuracy: 0.

27/27 [==============================] - 0s 2ms/step - loss: 0.3636 - accuracy: 0.8457
Epoch 558/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.3632 - accuracy: 0.8463
Epoch 559/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.3629 - accuracy: 0.8448
Epoch 560/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.3632 - accuracy: 0.8452
Epoch 561/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.3603 - accuracy: 0.8461
Epoch 562/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.3634 - accuracy: 0.8454
Epoch 563/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.3604 - accuracy: 0.8474
Epoch 564/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.3620 - accuracy: 0.8473
Epoch 565/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.3622 - accuracy: 0.8461
Epoch 566/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.3616 - accuracy: 0.

27/27 [==============================] - 0s 2ms/step - loss: 0.3624 - accuracy: 0.8458
Epoch 638/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.3624 - accuracy: 0.8457
Epoch 639/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.3593 - accuracy: 0.8479
Epoch 640/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.3601 - accuracy: 0.8461
Epoch 641/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.3619 - accuracy: 0.8458
Epoch 642/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.3606 - accuracy: 0.8469
Epoch 643/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.3698 - accuracy: 0.8417
Epoch 644/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.3617 - accuracy: 0.8463
Epoch 645/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.3605 - accuracy: 0.8477
Epoch 646/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.3587 - accuracy: 0.

27/27 [==============================] - 0s 2ms/step - loss: 0.3588 - accuracy: 0.8473
Epoch 718/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.3613 - accuracy: 0.8454
Epoch 719/1000
27/27 [==============================] - 0s 3ms/step - loss: 0.3677 - accuracy: 0.8420
Epoch 720/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.3581 - accuracy: 0.8476
Epoch 721/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.3586 - accuracy: 0.8471
Epoch 722/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.3588 - accuracy: 0.8482
Epoch 723/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.3595 - accuracy: 0.8478
Epoch 724/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.3614 - accuracy: 0.8470
Epoch 725/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.3592 - accuracy: 0.8482
Epoch 726/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.3610 - accuracy: 0.

27/27 [==============================] - 0s 2ms/step - loss: 0.3566 - accuracy: 0.8480
Epoch 798/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.3569 - accuracy: 0.8480
Epoch 799/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.3600 - accuracy: 0.8467
Epoch 800/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.3588 - accuracy: 0.8472
Epoch 801/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.3584 - accuracy: 0.8478
Epoch 802/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.3591 - accuracy: 0.8467
Epoch 803/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.3564 - accuracy: 0.8482
Epoch 804/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.3613 - accuracy: 0.8477
Epoch 805/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.3573 - accuracy: 0.8475
Epoch 806/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.3575 - accuracy: 0.

27/27 [==============================] - 0s 2ms/step - loss: 0.3572 - accuracy: 0.8481
Epoch 877/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.3571 - accuracy: 0.8471
Epoch 878/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.3581 - accuracy: 0.8480
Epoch 879/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.3573 - accuracy: 0.8478
Epoch 880/1000
27/27 [==============================] - 0s 3ms/step - loss: 0.3579 - accuracy: 0.8475
Epoch 881/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.3575 - accuracy: 0.8478
Epoch 882/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.3628 - accuracy: 0.8448
Epoch 883/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.3578 - accuracy: 0.8475
Epoch 884/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.3595 - accuracy: 0.8467
Epoch 885/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.3584 - accuracy: 0.

27/27 [==============================] - 0s 2ms/step - loss: 0.3589 - accuracy: 0.8485
Epoch 956/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.3543 - accuracy: 0.8489
Epoch 957/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.3557 - accuracy: 0.8493
Epoch 958/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.3558 - accuracy: 0.8487
Epoch 959/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.3553 - accuracy: 0.8487
Epoch 960/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.3556 - accuracy: 0.8488
Epoch 961/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.3548 - accuracy: 0.8489
Epoch 962/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.3561 - accuracy: 0.8492
Epoch 963/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.3558 - accuracy: 0.8481
Epoch 964/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.3584 - accuracy: 0.

In [56]:
prediction_h = ann.predict(c_imputed_test_feature_)
prediction_h

array([[0.17681292],
       [0.05986241],
       [0.5932546 ],
       ...,
       [0.14958102],
       [0.03120869],
       [0.6204405 ]], dtype=float32)

In [57]:
ann.fit(c_imputed_feature_, label_s, batch_size = 1024, epochs = 1000)

Epoch 1/1000
27/27 [==============================] - 0s 3ms/step - loss: 0.5614 - accuracy: 0.7239
Epoch 2/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.5120 - accuracy: 0.7519
Epoch 3/1000
27/27 [==============================] - 0s 3ms/step - loss: 0.5028 - accuracy: 0.7579
Epoch 4/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.4953 - accuracy: 0.7640
Epoch 5/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.4915 - accuracy: 0.7672
Epoch 6/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.4867 - accuracy: 0.7694
Epoch 7/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.4841 - accuracy: 0.7723
Epoch 8/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.4848 - accuracy: 0.7715
Epoch 9/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.4801 - accuracy: 0.7736
Epoch 10/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.4790 - accuracy: 0.7741

27/27 [==============================] - 0s 2ms/step - loss: 0.4623 - accuracy: 0.7856
Epoch 83/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.4603 - accuracy: 0.7857
Epoch 84/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.4618 - accuracy: 0.7859
Epoch 85/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.4596 - accuracy: 0.7862
Epoch 86/1000
27/27 [==============================] - 0s 3ms/step - loss: 0.4611 - accuracy: 0.7859
Epoch 87/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.4610 - accuracy: 0.7865
Epoch 88/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.4594 - accuracy: 0.7862
Epoch 89/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.4604 - accuracy: 0.7865
Epoch 90/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.4598 - accuracy: 0.7870
Epoch 91/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.4597 - accuracy: 0.7871
Epoc

27/27 [==============================] - 0s 2ms/step - loss: 0.4560 - accuracy: 0.7881
Epoch 162/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.4570 - accuracy: 0.7886
Epoch 163/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.4573 - accuracy: 0.7874
Epoch 164/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.4571 - accuracy: 0.7888
Epoch 165/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.4549 - accuracy: 0.7894
Epoch 166/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.4548 - accuracy: 0.7898
Epoch 167/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.4562 - accuracy: 0.7881
Epoch 168/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.4564 - accuracy: 0.7885
Epoch 169/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.4568 - accuracy: 0.7881
Epoch 170/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.4570 - accuracy: 0.

27/27 [==============================] - 0s 2ms/step - loss: 0.4528 - accuracy: 0.7903
Epoch 242/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.4526 - accuracy: 0.7910
Epoch 243/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.4535 - accuracy: 0.7908
Epoch 244/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.4525 - accuracy: 0.7909
Epoch 245/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.4530 - accuracy: 0.7899
Epoch 246/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.4521 - accuracy: 0.7917
Epoch 247/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.4534 - accuracy: 0.7907
Epoch 248/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.4539 - accuracy: 0.7895
Epoch 249/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.4543 - accuracy: 0.7902
Epoch 250/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.4558 - accuracy: 0.

27/27 [==============================] - 0s 2ms/step - loss: 0.4511 - accuracy: 0.7923
Epoch 322/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.4525 - accuracy: 0.7917
Epoch 323/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.4496 - accuracy: 0.7934
Epoch 324/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.4520 - accuracy: 0.7910
Epoch 325/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.4514 - accuracy: 0.7905
Epoch 326/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.4501 - accuracy: 0.7925
Epoch 327/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.4523 - accuracy: 0.7900
Epoch 328/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.4586 - accuracy: 0.7878
Epoch 329/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.4533 - accuracy: 0.7902
Epoch 330/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.4536 - accuracy: 0.

27/27 [==============================] - 0s 2ms/step - loss: 0.4506 - accuracy: 0.7907
Epoch 402/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.4496 - accuracy: 0.7926
Epoch 403/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.4494 - accuracy: 0.7920
Epoch 404/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.4500 - accuracy: 0.7907
Epoch 405/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.4506 - accuracy: 0.7919
Epoch 406/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.4527 - accuracy: 0.7919
Epoch 407/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.4498 - accuracy: 0.7929
Epoch 408/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.4480 - accuracy: 0.7931
Epoch 409/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.4491 - accuracy: 0.7916
Epoch 410/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.4519 - accuracy: 0.

27/27 [==============================] - 0s 2ms/step - loss: 0.4502 - accuracy: 0.7900
Epoch 480/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.4470 - accuracy: 0.7931
Epoch 481/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.4470 - accuracy: 0.7940
Epoch 482/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.4473 - accuracy: 0.7920
Epoch 483/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.4511 - accuracy: 0.7934
Epoch 484/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.4472 - accuracy: 0.7935
Epoch 485/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.4462 - accuracy: 0.7941
Epoch 486/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.4473 - accuracy: 0.7936
Epoch 487/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.4475 - accuracy: 0.7930
Epoch 488/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.4476 - accuracy: 0.

27/27 [==============================] - 0s 2ms/step - loss: 0.4461 - accuracy: 0.7931
Epoch 560/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.4464 - accuracy: 0.7920
Epoch 561/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.4477 - accuracy: 0.7915
Epoch 562/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.4490 - accuracy: 0.7928
Epoch 563/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.4499 - accuracy: 0.7908
Epoch 564/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.4462 - accuracy: 0.7926
Epoch 565/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.4461 - accuracy: 0.7949
Epoch 566/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.4448 - accuracy: 0.7952
Epoch 567/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.4486 - accuracy: 0.7935
Epoch 568/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.4453 - accuracy: 0.

27/27 [==============================] - 0s 2ms/step - loss: 0.4445 - accuracy: 0.7954
Epoch 640/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.4437 - accuracy: 0.7957
Epoch 641/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.4457 - accuracy: 0.7947
Epoch 642/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.4446 - accuracy: 0.7953
Epoch 643/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.4440 - accuracy: 0.7951
Epoch 644/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.4479 - accuracy: 0.7926
Epoch 645/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.4452 - accuracy: 0.7940
Epoch 646/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.4471 - accuracy: 0.7943
Epoch 647/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.4447 - accuracy: 0.7948
Epoch 648/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.4512 - accuracy: 0.

27/27 [==============================] - 0s 2ms/step - loss: 0.4474 - accuracy: 0.7931
Epoch 719/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.4434 - accuracy: 0.7950
Epoch 720/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.4447 - accuracy: 0.7947
Epoch 721/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.4429 - accuracy: 0.7956
Epoch 722/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.4432 - accuracy: 0.7953
Epoch 723/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.4426 - accuracy: 0.7962
Epoch 724/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.4436 - accuracy: 0.7957
Epoch 725/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.4423 - accuracy: 0.7958
Epoch 726/1000
27/27 [==============================] - 0s 3ms/step - loss: 0.4436 - accuracy: 0.7953
Epoch 727/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.4436 - accuracy: 0.

27/27 [==============================] - 0s 2ms/step - loss: 0.4416 - accuracy: 0.7959
Epoch 798/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.4408 - accuracy: 0.7968
Epoch 799/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.4433 - accuracy: 0.7963
Epoch 800/1000
27/27 [==============================] - ETA: 0s - loss: 0.4402 - accuracy: 0.79 - 0s 2ms/step - loss: 0.4401 - accuracy: 0.7975
Epoch 801/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.4407 - accuracy: 0.7975
Epoch 802/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.4423 - accuracy: 0.7962
Epoch 803/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.4412 - accuracy: 0.7970
Epoch 804/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.4409 - accuracy: 0.7960
Epoch 805/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.4421 - accuracy: 0.7962
Epoch 806/1000
27/27 [==============================] -

27/27 [==============================] - 0s 2ms/step - loss: 0.4403 - accuracy: 0.7968
Epoch 877/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.4403 - accuracy: 0.7977
Epoch 878/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.4419 - accuracy: 0.7966
Epoch 879/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.4394 - accuracy: 0.7987
Epoch 880/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.4424 - accuracy: 0.7957
Epoch 881/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.4401 - accuracy: 0.7980
Epoch 882/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.4397 - accuracy: 0.7969
Epoch 883/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.4424 - accuracy: 0.7968
Epoch 884/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.4404 - accuracy: 0.7981
Epoch 885/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.4389 - accuracy: 0.

27/27 [==============================] - 0s 2ms/step - loss: 0.4399 - accuracy: 0.7959
Epoch 957/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.4424 - accuracy: 0.7965
Epoch 958/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.4379 - accuracy: 0.7990
Epoch 959/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.4384 - accuracy: 0.7980
Epoch 960/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.4419 - accuracy: 0.7974
Epoch 961/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.4380 - accuracy: 0.7992
Epoch 962/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.4397 - accuracy: 0.7967
Epoch 963/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.4409 - accuracy: 0.7982
Epoch 964/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.4389 - accuracy: 0.7984
Epoch 965/1000
27/27 [==============================] - 0s 2ms/step - loss: 0.4375 - accuracy: 0.

In [58]:
prediction_s = ann.predict(c_imputed_test_feature_)
prediction_s

array([[0.31084982],
       [0.04545543],
       [0.61443835],
       ...,
       [0.05826578],
       [0.09606689],
       [0.37049076]], dtype=float32)

In [61]:
prediction_h = OneDimension(prediction_h)
prediction_s = OneDimension(prediction_s)

prediction = pd.DataFrame({"h1n1_vaccine": prediction_h,"seasonal_vaccine": prediction_s},index = test_feature.index)
prediction.head()

h1n1_vaccine  seasonal_vaccine
respondent_id                                
26707              0.176813          0.310850
26708              0.059862          0.045455
26709              0.593255          0.614438
26710              0.708776          0.761648
26711              0.235148          0.252782